data_path: '/mnt/dive/shared/xyxu/datasets/cars196'
savename: 'best'
arch: 'resnet50_frozen_normalize'
seed: 1
BS: 112
n_epochs: 200

group_name: 'LearnQ_fen'
k: 3
reduction: 8

tau: '[100, 1000]'
gamma: 0.3
decay: 0.002
key_val_decay: 0.002
que_decay: 0.001

ft_params_lr: 1e-5
new_params_lr: 1e-5

loss_emb_name: 'Margin'
loss_div_name: 'DivBD'
lam_div: 0.01

cn: 25
loss_margin_beta_lr: 5e-5

eval_begin: 69
eval_every: 1